---
- hosts: college-app
  # become: True
  tasks:
    - name: Start the container
      docker_container:
        name: college-app
        image: "hiclass.azurecr.io/college-app:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
